### ISSUE TITLE
Unable to use classes made outside of module

### ISSUE THREAD

**Issue by ebm539** [LachlanPaulsen/DSpirolateral#2]
The module uses predefined variable names (ie `dRootList`) to access items in a class. As I use my own class (and not the one included with the module) with different variable names, this means that the module cannot get the digital root list (eg) and therefore cannot draw spirolaterals with custom classes.

Could a function be added that takes the required variables (as opposed to taking an entire instance of a class)?

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "spirolateral.py", line 358, in draw_spirolateral
    self.spirolaterals[self.index].digital_root_list)
  File "/home/ethan/github-repos/spirolateral-program/lib/otherSpiroClass.py", line 114, in loadSpiro
    xLocationList, yLocationList = self.__drawBasicSpiro(spiroObject, self.ghostTurtle, self.centerPos, False)
  File "/home/ethan/github-repos/spirolateral-program/lib/otherSpiroClass.py", line 75, in __drawBasicSpiro
    for distance in spiroObject.dRootList:
AttributeError: 'Spirolateral' object has no attribute 'dRootList'
```

**Comment by LachlanPaulsen** [comment]
Have added the loadRawValues method to the spirolateral drawer which allows you to put in the raw Name, multiple and angle for the spirolateral to appear on screen
